language: android

jdk:
- oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-27
    - build-tools-27.0.3
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.m2

script:
- ./gradlew clean build testReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -F app -f app/build/reports/jacoco/report.xml
  - bash <(curl -s https://codecov.io/bash) -F core -f core/build/reports/jacoco/report.xml