language: android

jdk:
- oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.2
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.m2

script:
- ./gradlew clean build test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $TOKEN_CODECOV

secure: "MqRySgMSSTMpxD4ouZw3P4rHIxC5LzpHiT1LdPT7Yz4gPY4TmmGxf3QaLgZSWe5n6o4RGf3hDr76iANyMKKN2Hql6DOUq33aXGdj26JBZw+x+JTFtUbikm9NNT5PqFfObmtYNuHsJqxsdfEXtu4HyOuG7tc0hnj8IiDSKuaai+hFKDdyImuj+6MS89ydX2hDxrtJ0TtPQmCzOroWtd0MxpSmnQmpakGgPq71auDhB7rRt0WSWPWKOBZyEp+izYBx+xb+Rs8we62RQRtL7goeIJOxvHH2HlfQDWjcWoBUChdCs+D4yrtWLIlAp5qQRCmagkSTvdqmVM9RTVhQtsNOKIb/8e1k0vysBkjyIhkt+a5BfHGBSYj6AR+y11r/CqFZAvwMC/lN17fHlfVqH2FbBkY92Kg0xQK4RQ3BYF+GYRMfCrfGevAwrvX/bJ31qIi4FJo3/7sXs8LKELwFNczS+ve6bJAG8GRhnezSCKqpeDKx2exAxub+1Zlnr0HTvZpAmmarwiF49gSEbSGAZ7z5My4JJMioM/N0m2hz6kDL3lL5dQ9ti3zzAWBSAFEVfYLy+rvwnN2YBsQWZ8WE/aG5Sdrxaz50QjYNL0YBgqjVtrwfAqpXFkTHRgZl9tIKvri6Gq1WCo7PuLkVKT+uql71Y0j5pe0qeUV2sLgBVvIEhHA="
