# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  test-and-build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: default

    steps:
      - checkout

      - android/run-tests:
          test-command: ./gradlew ktlintCheck testDebug --continue

      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug

  upload-code-coverage:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: default

    steps:
      - run:
          name: Upload CodeCov data
          command: bash <(curl -s https://codecov.io/bash) -F app -f app/build/reports/jacoco/report.xml ; bash <(curl -s https://codecov.io/bash) -F core -f core/build/reports/jacoco/report.xml
          when: on_success

workflows:
  debug-build:
    jobs:
      - test-and-build
      - upload-code-coverage:
          requires:
            - test-and-build
