# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  test-and-build:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - android/run-tests:
          test-command: ./gradlew ktlintCheck testDebug --continue

      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug

workflows:
  debug-build:
    jobs:
      - test-and-build
